version: "3.9"

services:
  go-app:
    container_name: go-app
    image: trancends/expense-tracker:1.0.0
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
